Task 6-3
YuriiDDD/NewR pull request #2
Opened 2021-11-30 15:27 UTC by YuriiDDD

2021-11-30 17:32 UTC, Retro-kharkov1 requested changes

2021-11-30 17:32 UTC, Retro-kharkov1 commented on Task6-2/Program.cs
> +            Console.WriteLine("Всего обработано файлов: {0}.", Count);
Задача не доделана, задача очень интерестная, нету замены данных в файле.
и представь что у тебя один файл весит 5GB как решишь проблему?

2021-11-30 17:32 UTC, Retro-kharkov1 commented on FileWorks/Program.cs
>                      sw.WriteLine(str + " Was created" + lastChange + ",");
Что случиться с потоком если здесь упадет ошибка?

2021-11-30 17:32 UTC, Retro-kharkov1 commented on FileWorks/Program.cs
>                  string str = Path.GetFileName(files[i]);
Дату модификации не нашел

2021-12-01 12:05 UTC, YuriiDDD commented
New realese of FiguresIerarhy

2021-12-01 12:05 UTC, merged